blank_issues_enabled: false
contact_links:
  - name: 💬 GitHub Discussions
    url: https://github.com/voodu00/pulseprint-desktop-app/discussions
    about: Ask questions, share ideas, and connect with the community
  - name: 📚 Documentation
    url: https://github.com/voodu00/pulseprint-desktop-app/blob/main/README.md
    about: Read the documentation, features list, and roadmap
  - name: 🚀 Roadmap
    url: https://github.com/voodu00/pulseprint-desktop-app/blob/main/ROADMAP.md
    about: See our development plans and upcoming features