name: ❓ Question or Support
description: Ask a question about using PulsePrint Desktop
title: "[Question]: "
labels: ["question", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Have a question about PulsePrint Desktop? Please check our documentation first:
        - [README](https://github.com/voodu00/pulseprint-desktop-app/blob/main/README.md)
        - [Features](https://github.com/voodu00/pulseprint-desktop-app/blob/main/FEATURES.md)
        - [Roadmap](https://github.com/voodu00/pulseprint-desktop-app/blob/main/ROADMAP.md)
        - [Troubleshooting](https://github.com/voodu00/pulseprint-desktop-app#troubleshooting)

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please check the following before submitting
      options:
        - label: I have searched existing issues and discussions
          required: true
        - label: I have checked the documentation and troubleshooting guide
          required: true

  - type: dropdown
    id: category
    attributes:
      label: Question Category
      description: What type of question is this?
      options:
        - Installation/Setup
        - Printer Configuration
        - MQTT Connection
        - Dashboard Usage
        - Import/Export
        - Troubleshooting
        - Development/Contributing
        - Other
    validations:
      required: true

  - type: textarea
    id: question
    attributes:
      label: Your Question
      description: What would you like to know?
      placeholder: Please be as specific as possible
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context and Environment
      description: |
        Provide relevant details about your setup:
        - Operating System
        - PulsePrint Desktop version
        - Printer model(s)
        - What you've already tried
      placeholder: |
        OS: macOS 14.0
        Version: v0.1.0-alpha
        Printer: Bambu Lab X1C
        Tried: Checked IP address, verified access code

  - type: textarea
    id: additional
    attributes:
      label: Additional Information
      description: Any other details that might be relevant
      placeholder: Screenshots, error messages, or other helpful information