name: Test Self-Hosted Runner

# Run on PRs and manually for testing
on:
  workflow_dispatch:
  pull_request:
    branches: [main, develop]

jobs:
  test-runner:
    name: Test Self-Hosted Runner
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: System info (before setup)
        run: |
          echo "=== System Information ==="
          uname -a
          echo ""
          echo "=== Memory Usage ==="
          free -h
          echo ""
          echo "=== CPU Info ==="
          nproc
          echo ""
          echo "=== Disk Usage ==="
          df -h
          echo ""
          echo "=== Current PATH ==="
          echo $PATH

      - name: Setup self-hosted runner
        uses: ./.github/actions/setup-self-hosted

      - name: Install frontend dependencies
        run: |
          echo "=== Installing frontend dependencies ==="
          cd frontend-react
          yarn install --frozen-lockfile
          echo "✅ Dependencies installed successfully"

      - name: Resource usage after install
        run: |
          echo "=== Resource Usage After Install ==="
          free -h
          echo ""
          echo "=== Top memory consumers ==="
          ps aux --sort=-%mem | head -10

      - name: Quick build test
        run: |
          echo "=== Testing quick build ==="
          cd frontend-react
          echo "Building frontend..."
          yarn build
          echo "✅ Frontend build successful"
          echo ""
          echo "Testing Rust compilation..."
          cd ../src-tauri
          if cargo check; then
            echo "✅ Rust compilation check successful"
          else
            echo "❌ Rust compilation failed - this might be due to missing system dependencies"
            echo "Please ensure all required development packages are installed"
          fi
