name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

permissions:
  contents: read
  actions: read
  checks: write
  pull-requests: write

env:
  CARGO_TERM_COLOR: always

jobs:
  # ===================

  # BUILD JOBS (FIRST)
  # ===================
  build-frontend:
    name: Build Frontend
    # runs-on: ubuntu-latest
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'yarn'
          cache-dependency-path: frontend-react/yarn.lock

      - name: Install dependencies
        run: |
          cd frontend-react
          yarn install --frozen-lockfile

      - name: Build frontend
        run: |
          cd frontend-react
          yarn build

      - name: Upload frontend build
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build
          path: frontend-react/build/
          retention-days: 1

      - name: Cache yarn dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/yarn
            frontend-react/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('frontend-react/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

  build-rust:
    name: Build Rust
    # runs-on: ubuntu-latest
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev \
            build-essential \
            curl \
            wget \
            file \
            libxdo-dev \
            libssl-dev \
            libayatana-appindicator3-dev \
            librsvg2-dev

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Cache Rust dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            src-tauri/target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Build Rust (release)
        run: |
          cd src-tauri
          cargo build --release

      - name: Upload Rust build
        uses: actions/upload-artifact@v4
        with:
          name: rust-build
          path: src-tauri/target/release/
          retention-days: 1

  # ===================
  # QUALITY JOBS (DEPEND ON BUILDS)
  # ===================
  frontend-quality:
    name: Frontend Quality Checks
    # runs-on: ubuntu-latest
    runs-on: self-hosted
    needs: build-frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'yarn'
          cache-dependency-path: frontend-react/yarn.lock

      - name: Restore yarn cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/yarn
            frontend-react/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('frontend-react/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies (if needed)
        run: |
          cd frontend-react
          yarn install --frozen-lockfile --prefer-offline

      - name: Run ESLint
        run: |
          cd frontend-react
          yarn eslint src --ext .ts,.tsx --max-warnings 50

      - name: Run Prettier check
        run: |
          cd frontend-react
          yarn prettier --check "src/**/*.{ts,tsx,js,jsx,json,css,md}"

      - name: TypeScript compilation check
        run: |
          cd frontend-react
          yarn tsc --noEmit

      - name: Run tests
        run: |
          cd frontend-react
          yarn test --watchAll=false --coverage

      - name: Upload coverage reports
        uses: codecov/codecov-action@v4
        with:
          file: ./frontend-react/coverage/lcov.info
          flags: frontend
          name: frontend-coverage

  rust-quality:
    name: Rust Quality Checks
    # runs-on: ubuntu-latest
    runs-on: self-hosted
    needs: build-rust

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev \
            build-essential \
            curl \
            wget \
            file \
            libxdo-dev \
            libssl-dev \
            libayatana-appindicator3-dev \
            librsvg2-dev

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Cache Rust dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            src-tauri/target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Run Clippy
        run: |
          cd src-tauri
          cargo clippy --all-targets --all-features

      - name: Check formatting
        run: |
          cd src-tauri
          cargo fmt --all -- --check

      - name: Run tests
        run: |
          cd src-tauri
          cargo test

  # ===================
  # CROSS-PLATFORM RUST BUILDS (PARALLEL WITH FRONTEND)
  # ===================
  build-rust-cross-platform:
    name: Build Rust Cross-Platform
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            name: Linux
          # - os: windows-latest
          #   name: Windows
          # - os: macos-latest
          #   name: macOS
    # runs-on: ${{ matrix.os }}
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Linux dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev \
            build-essential \
            curl \
            wget \
            file \
            libxdo-dev \
            libssl-dev \
            libayatana-appindicator3-dev \
            librsvg2-dev

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Rust dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            src-tauri/target/
          key: ${{ matrix.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Build Rust (release)
        run: |
          cd src-tauri
          cargo build --release

      - name: Upload Rust build
        uses: actions/upload-artifact@v4
        with:
          name: rust-build-${{ matrix.os }}
          path: src-tauri/target/release/
          retention-days: 1

  # ===================
  # CROSS-PLATFORM TAURI BUILDS (DEPEND ON BOTH BUILDS)
  # ===================
  cross-platform-build:
    name: Cross-Platform Tauri Build
    needs: [build-frontend, build-rust-cross-platform]
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            name: Linux
          - os: windows-latest
            name: Windows
          - os: macos-latest
            name: macOS
    # runs-on: ${{ matrix.os }}
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'yarn'
          cache-dependency-path: frontend-react/yarn.lock

      - name: Download frontend build
        uses: actions/download-artifact@v4
        with:
          name: frontend-build
          path: frontend-react/build/

      - name: Download Rust build
        uses: actions/download-artifact@v4
        with:
          name: rust-build-${{ matrix.os }}
          path: src-tauri/target/release/

      - name: Install Linux dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev \
            build-essential \
            curl \
            wget \
            file \
            libxdo-dev \
            libssl-dev \
            libayatana-appindicator3-dev \
            librsvg2-dev

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Rust dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            src-tauri/target/
          key: ${{ matrix.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install Tauri CLI
        run: cargo install tauri-cli --locked

      - name: Build Tauri application
        run: |
          cd src-tauri
          # Use pre-built Rust binary and frontend build
          cargo tauri build --no-bundle --config '{"build":{"beforeBuildCommand":""}}'

  # ===================
  # INTEGRATION & E2E TESTS (DEPEND ON BUILDS)
  # ===================
  integration-tests:
    name: Integration Tests
    needs: [build-frontend, build-rust-cross-platform]
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            name: Linux
          - os: windows-latest
            name: Windows
          - os: macos-latest
            name: macOS
    # runs-on: ${{ matrix.os }}
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Linux dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev \
            build-essential \
            curl \
            wget \
            file \
            libxdo-dev \
            libssl-dev \
            libayatana-appindicator3-dev \
            librsvg2-dev

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Download Rust build
        uses: actions/download-artifact@v4
        with:
          name: rust-build-${{ matrix.os }}
          path: src-tauri/target/release/

      - name: Cache Rust dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            src-tauri/target/
          key: ${{ matrix.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Run Tauri integration tests
        run: |
          cd src-tauri
          cargo test --test integration_tests

  e2e-tests:
    name: E2E Tests (Playwright)
    needs: build-frontend
    # runs-on: ubuntu-latest
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'yarn'
          cache-dependency-path: frontend-react/yarn.lock

      - name: Download frontend build
        uses: actions/download-artifact@v4
        with:
          name: frontend-build
          path: frontend-react/build/

      - name: Restore yarn cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/yarn
            frontend-react/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('frontend-react/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies (if needed)
        run: |
          cd frontend-react
          yarn install --frozen-lockfile --prefer-offline

      - name: Install Playwright browsers
        run: |
          cd frontend-react
          yarn playwright install --with-deps

      - name: Run E2E tests
        run: |
          cd frontend-react
          yarn test:e2e

      - name: Upload Playwright report
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: playwright-report
          path: frontend-react/playwright-report/
          retention-days: 30
